# Generated by Django 4.2.23 on 2025-06-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('doffice', models.CharField(max_length=100)),
                ('dphone', models.CharField(max_length=20)),
                ('cstart_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_departments', to='main_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main_app.department'),
        ),
    ]
