# Generated by Django 4.2.23 on 2025-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_department_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('admission', 'In Admission'), ('graduate', 'Graduate'), ('archived', 'Archived'), ('transfer', 'Transferred')], default='admission', max_length=20, null=True),
        ),
    ]
